language: c++

os: linux
dist: bionic
addons:
  apt:
    packages:
      - cmake
      - clang-format
      - libssl-dev
      - ninja-build

script:
  - MLSPP_LINT=ON make
  - make gen
  - make test
